import React from "react";
import { Card, Col, Container, Row } from "react-bootstrap";
import { useLocation } from "react-router-dom";
import Tabla from "../componentes/tablas/Tabla";

const ResultadoEvento = () => {
  const location = useLocation();
  const {
    props: { id, fecha },
  } = location.state;
  

  let columnas6 = (
    <tr>
      <th>Pos</th>
      <th>Nombre</th>
      <th>Num</th>
      <th>Jinete</th>
      <th>Stud</th>
      <th>Tiempo</th>
      <th>Remate 300m</th>
      <th>Remate 400m</th>
      <th>Remate 800m</th>
    </tr>
  );

  const resultados = [
    {
      id: "1",
      nombre: "Carrera 1",
      posiciones: [
        {
          pos: 1,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "15:30",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 2,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 3,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 4,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 5,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 6,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 7,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 8,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 9,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 10,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 11,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 12,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 13,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 14,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
      ],
    },
    {
      id: "2",
      nombre: "Carrera 2",
      posiciones: [
        {
          pos: 1,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "15:30",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 2,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 3,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 4,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 5,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 6,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 7,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 8,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 9,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 10,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 11,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 12,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 13,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 14,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
      ],
    },
    {
      id: "3",
      nombre: "Carrera 3",
      posiciones: [
        {
          pos: 1,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "15:30",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 2,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 3,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 4,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 5,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 6,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 7,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 8,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 9,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 10,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 11,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 12,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 13,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 14,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
      ],
    },
    {
      id: "4",
      nombre: "Carrera 4",
      posiciones: [
        {
          pos: 1,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "15:30",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 2,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 3,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 4,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 5,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 6,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 7,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 8,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 9,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 10,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 11,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 12,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 13,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 14,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
      ],
    },
    {
      id: "5",
      nombre: "Carrera 5",
      posiciones: [
        {
          pos: 1,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "15:30",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 2,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 3,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 4,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 5,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 6,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 7,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 8,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 9,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 10,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
      ],
    },
    {
      id: "6",
      nombre: "Carrera 6",
      posiciones: [
        {
          pos: 1,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "15:30",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 2,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 3,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 4,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 5,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 6,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 7,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 8,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 9,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 10,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 11,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
        {
          pos: 12,
          nombre: "Wixy",
          num: 44,
          jinete: "Pedro Navaja",
          stud: "Papa Pedro",
          tiempo: "+1.4 seg",
          rem_300m: "42km/h",
          rem_400m: "40km/h",
          rem_800m: "436km/h",
        },
      ],
    },
  ];

  return (
    <Container>
      <Row className="text-center">
        <h1>{`RESULTADOS DEL EVENTO DEL ${fecha}`}</h1>
      </Row>

      <Row>
        <Col className="justify-content-center align-items-center mx-5">
          <Card>
            <Card.Body style={{ height: "500px", overflowY: "scroll" }}>
              <Row className="row row-cols-1">
                {resultados.map((x) => (
                  <Tabla
                    titulo={x.nombre}
                    columnas={columnas6}
                    informacion={x.posiciones}
                    funcion={(x) => (
                      <tr>
                        <td>{`${x.pos}`}</td>
                        <td>{`${x.nombre}`}</td>
                        <td>{`${x.num}`}</td>
                        <td>{`${x.jinete}`}</td>
                        <td>{`${x.stud}`}</td>
                        <td>{`${x.tiempo}`}</td>
                        <td>{`${x.rem_300m}`}</td>
                        <td>{`${x.rem_400m}`}</td>
                        <td>{`${x.rem_800m}`}</td>
                      </tr>
                    )}
                  ></Tabla>
                ))}
              </Row>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </Container>
  );
};

export default ResultadoEvento;
